server {
    listen 80;
    server_name trppowersplus.com www.trppowersplus.com;
    root /usr/share/nginx/html;
    index index.html;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location /admin {
        return 301 /admin/login;
    }

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }
}